### ISSUE TITLE
filter_ext函数过滤问题

### ISSUE THREAD

**Issue by LztCode** [minofmax/webVulnScanCrawler#3]
filter_ext函数仅仅是简单过滤，会导致例如www.tarschool.edu.cn等域名被全部过滤，因为其中含关键字tar

**Comment by LztCode** [comment]
用这个来取URL后缀名可能好一点， os.path.splitext(urllib.parse.urlparse(url).path)[-1]

**Comment by minofmax** [comment]
> 用这个来取URL后缀名可能好一点， os.path.splitext(urllib.parse.urlparse(url).path)[-1]

ok，这个我后面测了加进去，感谢建议
