### ISSUE TITLE
md5去重影响效率

### ISSUE THREAD

**Issue by LztCode** [minofmax/webVulnScanCrawler#4]

**Comment by LztCode** [comment]
md5涉及大量cpu计算，应对大型网站时爬虫会占用大量cpu资源，我的想法是再追加一个布隆过滤器，而不使用md5

**Comment by minofmax** [comment]
这个可以，md5计算影响使用协程去做异步。布隆也不太好处理，因为有些url是api接口，也有可能是前端静态路由，更难受的是我遇到过一模一样的，这个既是前端路由，也是动态接口
