### ISSUE TITLE
协程效率较低

### ISSUE THREAD

**Issue by LztCode** [minofmax/webVulnScanCrawler#5]
使用嵌套异步可以加速爬取过程
如
假设_crawler_handler(self, url)的url是传入一个url列表，则使用嵌套异步：
tasks = [asyncio.ensure_future(parse_page(page, domain, semaphore)) for domain in url]
await asyncio.wait(tasks)

注: parse_page是异步的 with sync_playwright() as p  封装函数
注: sync_playwright() => async_playwright()

**Comment by minofmax** [comment]
涉及计算，协程其实也解决不了太多问题，可以考虑多进程做异步非阻塞的，线程安全在代码逻辑保证，最近没时间改，这一版还是有些问题

**Comment by LztCode** [comment]
如果能够使用一些逻辑去重方式能不能避免这个计算，如：
用一个特殊的思路来处理
使用A来代表纯数字，B来代表字符串
如果两个链接中只有A相同，那么则相似
如果只有B相同，则认为不相似

**Comment by minofmax** [comment]
> 如果能够使用一些逻辑去重方式能不能避免这个计算，如：
> 用一个特殊的思路来处理
> 使用A来代表纯数字，B来代表字符串
> 如果两个链接中只有A相同，那么则相似
> 如果只有B相同，则认为不相似

**Comment by minofmax** [comment]
> 如果能够使用一些逻辑去重方式能不能避免这个计算，如：
> 用一个特殊的思路来处理
> 使用A来代表纯数字，B来代表字符串
> 如果两个链接中只有A相同，那么则相似
> 如果只有B相同，则认为不相似

其实比较也是计算，其他的就是url比较，我个人认为涉及三个方面，协议、域名、uri，uri还得对querystring去做参数去重。之前考虑过用汉明距离去做url去重，但是发现也不是很靠谱

**Comment by LztCode** [comment]
> > 如果能够使用一些逻辑去重方式能不能避免这个计算，如：
> > 用一个特殊的思路来处理
> > 使用A来代表纯数字，B来代表字符串
> > 如果两个链接中只有A相同，那么则相似
> > 如果只有B相同，则认为不相似
> 
> 其实比较也是计算，其他的就是url比较，我个人认为涉及三个方面，协议、域名、uri，uri还得对querystring去做参数去重。之前考虑过用汉明距离去做url去重，但是发现也不是很靠谱

可不可以先取尽量多的url再统一进行计算去重，每一步都去重非常耗时

**Comment by minofmax** [comment]
> > > 如果能够使用一些逻辑去重方式能不能避免这个计算，如：
> > > 用一个特殊的思路来处理
> > > 使用A来代表纯数字，B来代表字符串
> > > 如果两个链接中只有A相同，那么则相似
> > > 如果只有B相同，则认为不相似
> > 
> > 
> > 其实比较也是计算，其他的就是url比较，我个人认为涉及三个方面，协议、域名、uri，uri还得对querystring去做参数去重。之前考虑过用汉明距离去做url去重，但是发现也不是很靠谱
> 
> 可不可以先取尽量多的url再统一进行计算去重，每一步都去重非常耗时

可以通过统一计算去重来保证在请求过程中没有计算，这个可行，在每轮url访问结束后，统一计算去重，然后确定下一轮待爬的队列。其实去重现在倒不是很耗时，因为用的字典，算法复杂度是O(1)

**Comment by LztCode** [comment]
> > > > 如果能够使用一些逻辑去重方式能不能避免这个计算，如：
> > > > 用一个特殊的思路来处理
> > > > 使用A来代表纯数字，B来代表字符串
> > > > 如果两个链接中只有A相同，那么则相似
> > > > 如果只有B相同，则认为不相似
> > > 
> > > 
> > > 其实比较也是计算，其他的就是url比较，我个人认为涉及三个方面，协议、域名、uri，uri还得对querystring去做参数去重。之前考虑过用汉明距离去做url去重，但是发现也不是很靠谱
> > 
> > 
> > 可不可以先取尽量多的url再统一进行计算去重，每一步都去重非常耗时
> 
> 可以通过统一计算去重来保证在请求过程中没有计算，这个可行，在每轮url访问结束后，统一计算去重，然后确定下一轮待爬的队列。其实去重现在倒不是很耗时，因为用的字典，算法复杂度是O(1)

后续还应该做页面404判断的，如果每一次请求都进行计算，再做利用余弦相似性算法等做404判断，耗时就增加了

**Comment by minofmax** [comment]
> > > > > 如果能够使用一些逻辑去重方式能不能避免这个计算，如：
> > > > > 用一个特殊的思路来处理
> > > > > 使用A来代表纯数字，B来代表字符串
> > > > > 如果两个链接中只有A相同，那么则相似
> > > > > 如果只有B相同，则认为不相似
> > > > 
> > > > 
> > > > 其实比较也是计算，其他的就是url比较，我个人认为涉及三个方面，协议、域名、uri，uri还得对querystring去做参数去重。之前考虑过用汉明距离去做url去重，但是发现也不是很靠谱
> > > 
> > > 
> > > 可不可以先取尽量多的url再统一进行计算去重，每一步都去重非常耗时
> > 
> > 
> > 可以通过统一计算去重来保证在请求过程中没有计算，这个可行，在每轮url访问结束后，统一计算去重，然后确定下一轮待爬的队列。其实去重现在倒不是很耗时，因为用的字典，算法复杂度是O(1)
> 
> 后续还应该做页面404判断的，如果每一次请求都进行计算，再做利用余弦相似性算法等做404判断，耗时就增加了

这个在公司做的爬虫是做了，我这个版本只是很简单的一个逻辑，页面相似度算法还挺多的，百度有一篇工程论文，写这个，还不错，好像叫页面相似度检测。
