### ISSUE TITLE
有些网站加载不了图片会一直轮询加载的问题

### ISSUE THREAD

**Issue by LztCode** [minofmax/webVulnScanCrawler#6]
用这个route.fulfill，拦截响应包，修改响应码为204，实测能提高网站爬行速度

'''请求过滤'''
if resource_type in ['image', 'media', 'eventsource', 'websocket']:
    route.abort() # 这条语句 => route.fulfill(status=204)

注： route.fulfill(status=204) # 防止页面加载图片，快速提高爬行效率

**Comment by minofmax** [comment]
> 用这个route.fulfill，拦截响应包，修改响应码为204，实测能提高网站爬行速度
> 
> '''请求过滤'''
> if resource_type in ['image', 'media', 'eventsource', 'websocket']:
> route.abort() # 这条语句 => route.fulfill(status=204)
> 
> 注： route.fulfill(status=204) # 防止页面加载图片，快速提高爬行效率

是的，也可以用在防止页面跳转或者刷新上面

**Comment by minofmax** [comment]
> 用这个route.fulfill，拦截响应包，修改响应码为204，实测能提高网站爬行速度
> 
> '''请求过滤'''
> if resource_type in ['image', 'media', 'eventsource', 'websocket']:
> route.abort() # 这条语句 => route.fulfill(status=204)
> 
> 注： route.fulfill(status=204) # 防止页面加载图片，快速提高爬行效率

如果你愿意，可以修改完合进来，优化一个更好的版本。
